//@version=4
strategy("{{config.name}}", overlay=true, calc_on_every_tick=true, initial_capital=1000, default_qty_value=100, default_qty_type=strategy.cash, currency=currency.USD)

// days to test
daysBackMax = input(defval=90, title="Max Days Back to Test", minval=0)
daysBackMin = input(defval=0, title="Min Days Back to Test", minval=0)
msBackMax = 1000 * 60 * 60 * 24 * daysBackMax
msBackMin = 1000 * 60 * 60 * 24 * daysBackMin
isWithinTimeBounds = (msBackMax == 0 or (time > (timenow - msBackMax))) and (msBackMin == 0 or (time < (timenow - msBackMin)))

// let's be responsible
longTakeProfPerc = input({{config.longTakeProfPerc}}, title='Long Take Profit %', type=input.float, step=1) / 100
longTakeProfPrice = strategy.position_avg_price * (1 + longTakeProfPerc)

var isLong = false
var isShort = false

// MACD
fast = 12, slow = 26
fastMA = ema(close, fast)
slowMA = ema(close, slow)
macd = fastMA - slowMA

getMACD(index) =>
    thisFastMA = ema(close[index], fast)
    thisSlowMA = ema(close[index], slow)
    thisMacd = thisFastMA - thisSlowMA

macd0 = getMACD(0)
macd1 = getMACD(1)
macd2 = getMACD(2)
macd3 = getMACD(3)
// macd4 = getMACD(4)
signal = ema(macd, 9)

macdUp = macd0 > macd1 and macd1 > macd2 and macd2 > macd3 and macd0 < 0 and macd > signal
macdDown = macd0 < macd1 and macd1 < macd2 and macd2 < macd3 and macd0 > 0

greenCandle = (close > open)
redCandle = (close < open)

// plot(macd, color=color.blue)
// plot(signal, color=color.orange)

long = not isLong and macdUp and greenCandle
short = not isShort and macdDown and redCandle

// plotshape(long, title="Mark", text="Mark", style=shape.labelup, location=location.belowbar, size=size.tiny, color=color.green, textcolor=color.white, transp=0)

if long
    isLong := true
    isShort := false

if short
    isLong := false
    isShort := true

strategy.entry("long", long=true, when=long and isWithinTimeBounds)
strategy.close("long", when=short or high > longTakeProfPrice and isWithinTimeBounds)