//@version=4
strategy("XMRBTC SMA Cross Strategy", overlay=true, calc_on_every_tick=false, initial_capital=1000, default_qty_value=100, default_qty_type=strategy.cash, currency=currency.USD)

// days to test
daysBackMax = input(defval=120, title="Max Days Back to Test", minval=0)
daysBackMin = input(defval=0, title="Min Days Back to Test", minval=0)
msBackMax = 1000 * 60 * 60 * 24 * daysBackMax
msBackMin = 1000 * 60 * 60 * 24 * daysBackMin
isWithinTimeBounds = (msBackMax == 0 or (time > (timenow - msBackMax))) and (msBackMin == 0 or (time < (timenow - msBackMin)))

// let's be responsible
// longLossPerc = input(12.0, title='Long Stop Loss %', type=input.float, step=1) / 120
// shortLossPerc = input(12.0, title='Short Stop Loss %', type=input.float, step=1) / 100
// longStopPrice = strategy.position_avg_price * (1 - longLossPerc)
// shortStopPrice = strategy.position_avg_price * (1 + shortLossPerc)
smaLength = input(defval=3, title="SMA Length", minval=0, step=3)

var isLong = false
var isShort = false

greenCandle = (close > open)
redCandle = (close < open)

sma = sma(close, smaLength)

plot(sma, linewidth=1, color=color.orange)

long = not isLong and open > sma and greenCandle
short = not isShort and open < sma and redCandle

bgcolor(color=long ? color.green : na)
bgcolor(color=short ? color.red : na)

if long
    isLong := true
    isShort := false

if short
    isLong := false
    isShort := true

strategy.entry("long", long=true, when=long and isWithinTimeBounds)
strategy.close("long", when=short and isWithinTimeBounds)
strategy.entry("short", long=false, when=short and isWithinTimeBounds)
strategy.close("short", when=long and isWithinTimeBounds)

// if (strategy.position_size > 0)
//     strategy.exit(id="stop buy", stop=longStopPrice)

// if (strategy.position_size < 0)
//     strategy.exit(id="stop sell", stop=shortStopPrice)